### PR TITLE
use trust's CI template as base for our CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 895ed02 with merge 895ed02...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/smoke/builds/168190737)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b9c5e42 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b9c5e42 with merge b9c5e42...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 2f3b857 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 2f3b857 with merge 2f3b857...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/smoke/builds/168338690)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit a1cb9b0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit a1cb9b0 with merge a1cb9b0...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/smoke/builds/169440799)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 97e88a7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 97e88a7 with merge 97e88a7...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit eefe828 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit eefe828 with merge eefe828...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/smoke/builds/169563280)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 38425bf has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 38425bf with merge 38425bf...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/smoke/builds/174115116)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 0a70aaf with merge 0a70aaf...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/smoke/builds/176448182)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 5735394 with merge 5735394...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/smoke/builds/176487416)

**Comment by japaric** [comment]
This is still red but most of the other errors are legit so I'm going to merge this anyway.

**Pull request merged**
